console.log("Avanzar");
console.log("Llenar 1");
console.log("Avanzar");
console.log("Avanzar");
console.log("Avanzar");
console.log("Llenar 1");
console.log("Avanzar");
console.log("Quitar 1");
console.log("Avanzar");
console.log("Quitar 1");
console.log("Avanzar");
console.log("FIN Ejercicio 2:");
