console.log("Avanzar");
console.log("Quitar 1");
console.log("Avanzar");
console.log("Quitar 1");
console.log("Avanzar");
console.log("Quitar 1");
console.log("Avanzar");
console.log("Quitar 1");
console.log("Girar Izquierda 90°");
console.log("Avanzar");
console.log("Quitar 1");
console.log("Avanzar");
console.log("Quitar 1");
console.log("Avanzar");
console.log("Quitar 1");
console.log("Avanzar");
console.log("Quitar 1");
console.log("Avanzar");
console.log("Quitar 1");
console.log("FIN Ejercicio 1:");
